// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.19.4
// source: protos/ms.proto

package protos

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MyProduct struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Nnber int32 `protobuf:"varint,1,opt,name=nnber,proto3" json:"nnber,omitempty"`
}

func (x *MyProduct) Reset() {
	*x = MyProduct{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_ms_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MyProduct) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MyProduct) ProtoMessage() {}

func (x *MyProduct) ProtoReflect() protoreflect.Message {
	mi := &file_protos_ms_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MyProduct.ProtoReflect.Descriptor instead.
func (*MyProduct) Descriptor() ([]byte, []int) {
	return file_protos_ms_proto_rawDescGZIP(), []int{0}
}

func (x *MyProduct) GetNnber() int32 {
	if x != nil {
		return x.Nnber
	}
	return 0
}

type MyConsumer struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Mmber int32 `protobuf:"varint,1,opt,name=mmber,proto3" json:"mmber,omitempty"`
}

func (x *MyConsumer) Reset() {
	*x = MyConsumer{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_ms_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MyConsumer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MyConsumer) ProtoMessage() {}

func (x *MyConsumer) ProtoReflect() protoreflect.Message {
	mi := &file_protos_ms_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MyConsumer.ProtoReflect.Descriptor instead.
func (*MyConsumer) Descriptor() ([]byte, []int) {
	return file_protos_ms_proto_rawDescGZIP(), []int{1}
}

func (x *MyConsumer) GetMmber() int32 {
	if x != nil {
		return x.Mmber
	}
	return 0
}

var File_protos_ms_proto protoreflect.FileDescriptor

var file_protos_ms_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f, 0x6d, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x22, 0x21, 0x0a, 0x09, 0x4d, 0x79, 0x50,
	0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x6e, 0x6e, 0x62, 0x65, 0x72, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x6e, 0x6e, 0x62, 0x65, 0x72, 0x22, 0x22, 0x0a, 0x0a,
	0x4d, 0x79, 0x43, 0x6f, 0x6e, 0x73, 0x75, 0x6d, 0x65, 0x72, 0x12, 0x14, 0x0a, 0x05, 0x6d, 0x6d,
	0x62, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x6d, 0x6d, 0x62, 0x65, 0x72,
	0x32, 0x3e, 0x0a, 0x07, 0x47, 0x72, 0x65, 0x65, 0x74, 0x65, 0x72, 0x12, 0x33, 0x0a, 0x08, 0x43,
	0x6f, 0x6e, 0x54, 0x6f, 0x50, 0x72, 0x6f, 0x12, 0x12, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73,
	0x2e, 0x4d, 0x79, 0x43, 0x6f, 0x6e, 0x73, 0x75, 0x6d, 0x65, 0x72, 0x1a, 0x11, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x4d, 0x79, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x22, 0x00,
	0x42, 0x0a, 0x5a, 0x08, 0x2e, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_protos_ms_proto_rawDescOnce sync.Once
	file_protos_ms_proto_rawDescData = file_protos_ms_proto_rawDesc
)

func file_protos_ms_proto_rawDescGZIP() []byte {
	file_protos_ms_proto_rawDescOnce.Do(func() {
		file_protos_ms_proto_rawDescData = protoimpl.X.CompressGZIP(file_protos_ms_proto_rawDescData)
	})
	return file_protos_ms_proto_rawDescData
}

var file_protos_ms_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_protos_ms_proto_goTypes = []interface{}{
	(*MyProduct)(nil),  // 0: protos.MyProduct
	(*MyConsumer)(nil), // 1: protos.MyConsumer
}
var file_protos_ms_proto_depIdxs = []int32{
	1, // 0: protos.Greeter.ConToPro:input_type -> protos.MyConsumer
	0, // 1: protos.Greeter.ConToPro:output_type -> protos.MyProduct
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_protos_ms_proto_init() }
func file_protos_ms_proto_init() {
	if File_protos_ms_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_protos_ms_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MyProduct); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_ms_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MyConsumer); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_protos_ms_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_protos_ms_proto_goTypes,
		DependencyIndexes: file_protos_ms_proto_depIdxs,
		MessageInfos:      file_protos_ms_proto_msgTypes,
	}.Build()
	File_protos_ms_proto = out.File
	file_protos_ms_proto_rawDesc = nil
	file_protos_ms_proto_goTypes = nil
	file_protos_ms_proto_depIdxs = nil
}
